### ISSUE TITLE
How to set up a breakpoint?

### ISSUE THREAD

**Issue by NoAnyLove** [Tuplanolla/cheat#5]
According to section 5.6 Debugging, it's impossible to attach a breakpoint to
any of the identifiers, but we can attach one to `CHEAT_GET(name)` or `cheat_check()` instead.

The documentation doesn't explain in detail, so I'm still confused about how to do that.

For example, if I have code below, could you please explain how to set up a breakpoint on `t=t+1`? Or how to break on `test_add`?

```c
#include "cheat.h"
#include "cheats.h"

CHEAT_TEST(test_add,
        int t=0;
        t=t+1;
        assert(t > 0);
        )
```

**Comment by Tuplanolla** [comment]
It is generally not a good idea to debug tests,
but this is how you can attach breakpoints to either procedure.

    $ cat test.c
    #include "cheat.h"
    #include "cheats.h"

    CHEAT_TEST(test_add,
        int t = 0;
        t = t + 1;
        cheat_assert(t > 0);
    )
    $ gcc -I . -g3 -gdwarf-2 -o test test.c
    $ gdb --quiet --args ./test --unsafe
    Reading symbols from ./test...done.
    (gdb) list
    (gdb) macro expand CHEAT_GET(test_add)
    expands to: (cheat_test_test_add)
    (gdb) break cheat_test_test_add
    Breakpoint 1 at 0x40710b: file test.c, line 4.
    (gdb) run
    Starting program: /tmp/test --unsafe

    Breakpoint 1, cheat_test_test_add () at test.c:4
    4	CHEAT_TEST(test_add,
    (gdb) macro expand cheat_assert(t > 0)
    expands to: cheat_check(&cheat_suite, t > 0, "t > 0", "/tmp/test.c", 4)
    (gdb) break cheat_check
    Breakpoint 2 at 0x403e38: file /usr/local/include/cheat.h, line 1873.
    (gdb) continue
    Continuing.

I use `--unsafe` to prevent the monitoring process
from terminating the test while it is being debugged.
(setting `CHEAT_TIME` to a large value in CHEAT and
`follow-fork-mode` to `child` in GDB would work too).
Note that bringing preprocessor directives into GDB to call `CHEAT_GET` in it
requires compiling with `-g3 -gdwarf-2` instead of just `-g`.
This is not mandatory if you know how `CHEAT_GET` is defined.

**Comment by NoAnyLove** [comment]
I got it, thanks very much

**Comment by Tuplanolla** [comment]
Great. I might put a mention of this into the user manual if I get another release done.
