### ISSUE TITLE
How to test code from a separate file?

### ISSUE THREAD

**Issue by jhgorse** [Tuplanolla/cheat#7]
CHEAT works great for code defined within the CHEAT_DECLARE() macro.

What about code that comes from a separate .c file?

How do we use CHEAT with larger projects to test specific functions in other .c files? I am hoping that it is not to copy-paste into the CHEAT_DECLARE() macro.

Cheers,
Joe

**Comment by Tuplanolla** [comment]
You build the separate source file independently and
link it with the test suite, just like you would
when working with a procedure from the standard library.
It helps if your source file has an associated header,
much like bits of the standard library,
so that you do not need to redeclare its procedures in the test suite.

**Comment by jhgorse** [comment]
@Tuplanolla I forgot to guard one of my header files. So when the preprocessor sucked in the code it was causing trouble. It does make sense that we will need header guards in this case, since this is made possible with a minor abuse of the pre-processor. =)

All is well now. Thanks!

Cheers,
Joe
